version: "3"

services:
  php:
    image: previousnext/php:7.2-dev
    # This makes the container run on the same network stack as your
    # workstation. Meaning that you can interact on "localhost".
    network_mode: host
    volumes:
      - .:/data
    environment:
      - SIMPLETEST_BASE_URL=http://127.0.0.1
      - SIMPLETEST_DB=mysql://drupal:drupal@127.0.0.1/local
      - BROWSERTEST_OUTPUT_DIRECTORY=/data/app/sites/simpletest/browser_output
      - MINK_DRIVER_ARGS=["http:\/\/127.0.0.1:8510", "\/tmp"]
      - PHP_IDE_CONFIG=serverName=127.0.0.1
      - PHP_XDEBUG_AUTOSTART=1
      - XDEBUG_CONFIG=remote_host=127.0.0.1

  db:
    image: mariadb
    network_mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=local
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    #    volumes:
    #      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql or sql.gz file(s) here.

  mail:
    image: mailhog/mailhog
    network_mode: host

#  varnish:
#    image: previousnext/varnish:4.x-dev
#    network_mode: host

#  memcache:
#    image: memcached:1.4-alpine
#    network_mode: host

#  phantomjs:
#    image: previousnext/gastonjs:1.0.2
#    network_mode: host

  chrome:
    image: blueimp/chromedriver
    network_mode: host

#  search:
#    image: previousnext/solr:5.x
#    network_mode: host
