version: "3"

services:
  app:
    image: previousnext/php:7.2-dev
    # This makes the container run on the same network stack as your
    # workstation. Meaning that you can interact on "localhost".
    network_mode: host
    volumes:
      - .:/data
    environment:
      - SIMPLETEST_BASE_URL=http://127.0.0.1
      - SIMPLETEST_DB=mysql://drupal:drupal@127.0.0.1/local
      - BROWSERTEST_OUTPUT_DIRECTORY=/data/app/sites/simpletest/browser_output
      - MINK_DRIVER_ARGS=
      - MINK_DRIVER_ARGS_WEBDRIVER=["chrome", null, "http:\/\/127.0.0.1:4444\/wd\/hub"]
      - PHP_IDE_CONFIG=serverName=127.0.0.1
      - PHP_XDEBUG_AUTOSTART=1
      - XDEBUG_CONFIG=remote_host=127.0.0.1
      - PATH=$PATH:/data/bin:/data/app/vendor/bin
      - DRUSH_OPTIONS_URI=http://127.0.0.1

  db:
    image: mariadb
    network_mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=local
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal

  mail:
    image: mailhog/mailhog
    network_mode: host

  chrome:
    image: selenium/standalone-chrome
    network_mode: host
